### ISSUE TITLE
add mute-groups infos in the manual

### ISSUE THREAD

**Issue by Animtim** [ahlstromcj/sequencer64-doc#1]
While reading the doc looking for mute-group infos, I found: "One thing we need to discover is just what this mute-grouping means functionally. Apparently groups work with the playing screen set only. Change the screenset and give the command to make it the playing one (e.g. set the HOME key for this purpose.)"

After investigating, here is a proposal of explanation for mute groups:

Mute groups are shortcuts to play a defined group of patterns on current set while stopping patterns from other sets. 

To define the group of patterns for one mute group, keep pressing the Learn key (Insert key) and press one of the mute group keys: it will save the currently playing pattern slots in the corresponding mute group. 
Note that the default mute group keys need the Shift modifier, but you don't need it while pressing Insert to learn the group, only to trigger it (it will automatically assign the corresponding key with shift). 

Group-mute can be globally enabled or disabled (with default keys apostrophe and igrave). So make sure it is enabled before trying to use it.

Sorry for not providing a patch, I hope it already helps

**Comment by ahlstromcj** [comment]
Cool! Will update it ASAP (after work :-D)

**Comment by Animtim** [comment]
Nice, thanks.

One little precision, first line could be:
Mute groups are shortcuts to play a defined group of patterns on current set while stopping other patterns from current set and all patterns from other sets. 
(it may be better said, but at least that's more accurate)

**Comment by Animtim** [comment]
Also before opening another ticket: I noticed that the doc says the midi channel for control map values is stripped and not used. I checked that, as I needed different channels to map an APC40, and looks like channel values are read and works perfectly :) . Is it something that's been improved recently?

Note: I'm using 0.90.1  2017-02-26 0.90.1-0-g9ce0f8c * master

I'm very happy, because I could map usefully all the remaining controls on this device that were not relevant for ardour (the button grid and a few other buttons), it can now control ardour+seq64 combo :)
I'll share my rc with midi map soon, if someone is interested.

**Comment by ahlstromcj** [comment]
Hmmm, is there anyway to build seq24 and see how it works?  I could swear I
had seen the code that strips the channels, and wondered, why do that,
seemingly needlessly?  I can check this weekend, though, if you don't have
time.

If seq24 strips 'em, and seq64 doesn't, then that sounds like a new feature,
and maybe an option!

-------- Animtim 09:56 Fri 14 Apr      --------

>Also before opening another ticket: I noticed that the doc says the midi channel for control map values is stripped and not used. I checked that, as I needed different channels to map an APC40, and looks like channel values are read and works perfectly :) . Is it something that's been improved recently?
>
>Note: I'm using 0.90.1  2017-02-26 0.90.1-0-g9ce0f8c * master
>
>I'm very happy, because I could map usefully all the remaining controls on this device that were not relevant for ardour (the button grid and a few other buttons), it can now control ardour+seq64 combo :)
>I'll share my rc with midi map soon, if someone is interested.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64-doc/issues/1#issuecomment-294190509

-- 
Writing is turning one's worst moments into money.
		-- J.P. Donleavy

**Comment by Animtim** [comment]
Indeed, I just tried with a build of seq24 0.9.3, and looks like all the controls act on channel 1 (and not even properly, I see the pattern blink but it doesn't actually toggle.. but that's enough feedback to see all the controls do act on channel 1 ;) )

**Comment by ahlstromcj** [comment]
Just to make sure, you're saying no matter what channel the MIDI Control
comes in on in seq24, it acts only as channel 1, correct?  That would seem
to mean that seq24 does ignore the channel, I think.  Does that sound right?
Thanks!!!

-------- Animtim 10:28 Fri 14 Apr      --------

>Indeed, I just tried with a build of seq24 0.9.3, and looks like all the controls act on channel 1 (and not even properly, I see the pattern blink but it doesn't actually toggle.. but that's enough feedback to see all the controls do act on channel 1 ;) )
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ahlstromcj/sequencer64-doc/issues/1#issuecomment-294196880

-- 
Q:	How did you get into artificial intelligence?
A:	Seemed logical -- I didn't have any real intelligence.

**Comment by Animtim** [comment]
yep, exactly that

**Comment by Animtim** [comment]
For reference, I just pushed my rc file here: https://github.com/Animtim/apc40-linux
:)

**Comment by ahlstromcj** [comment]
Great! Many thanks!

**Comment by ahlstromcj** [comment]
Well, you actually helped me find a real bug!  Trying to figure out why channel wasn't being filtered in MIDI control, I found that a function that filtered the channel would convert all Note On velocities less than 16 to Note Offs, due to applying an unnecessary channel mask.  So bad, I backported this fix to master as well!  Thanks!  Now to fix up the documentation.
